package com.med.qa.controller.dto;

import org.springframework.lang.Nullable;

import java.util.List;

/**
 * The full eligibility assessment for a claim's line items.
 *
 * <p>{@code disclaimer} is always populated with the same fixed advisory statement — this is
 * decision support for a human claims reviewer, never an automated approval or denial, and the
 * field exists specifically so no caller can silently drop that framing when displaying results.</p>
 *
 * @param claimId     echoes the caller-supplied claim id, or {@code null} if none was given
 * @param assessments one assessment per submitted line item, in the same order as the request
 * @param disclaimer  fixed advisory statement, always non-null
 */
public record ClaimEligibilityResponse(
        @Nullable String claimId,
        List<ClaimItemAssessment> assessments,
        String disclaimer) {

    /** The fixed advisory statement attached to every response. */
    public static final String ADVISORY_DISCLAIMER =
            "This assessment is generated by an AI model for claims-reviewer decision support only. "
                    + "It is not a coverage determination. A qualified human reviewer must verify every "
                    + "item against the full policy wording before any approval or denial is communicated "
                    + "to a policyholder.";
}
